web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'apps.xnkpeyx0.canadacentral.aroapp.io'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://apps.xnkpeyx0.canadacentral.aroapp.io'
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab:Z'
    - '/srv/gitlab/logs:/var/log/gitlab:Z'
    - '/srv/gitlab/data:/var/opt/gitlab:Z'
